#version 450
layout(local_size_x = 16, local_size_y = 16) in;
layout(std430, binding = 0) readonly  buffer A { float a[]; };
layout(std430, binding = 1) readonly  buffer B { float b[]; };
layout(std430, binding = 2) writeonly buffer C { float c[]; };
layout(std430, binding = 3) readonly  buffer D { uint M; uint N; uint K; };
void main() {
    uint col = gl_GlobalInvocationID.x;
    uint row = gl_GlobalInvocationID.y;
    if (row >= M || col >= N) return;
    float s = 0.0;
    for (uint k = 0; k < K; k++) s += a[row*K + k] * b[k*N + col];
    c[row*N + col] = s;
}
